plugins { id 'com.android.application' }
android {
    namespace 'br.streamtv.central'
    compileSdk 35
    defaultConfig {
        applicationId 'br.streamtv.central'
        minSdk 23
        targetSdk 35
        versionCode 100
        versionName '1.0.0'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
