plugins { id 'com.android.application' }
android {
    namespace 'br.streamtv.app'
    compileSdk 35
    defaultConfig {
        applicationId 'br.streamtv.app'
        minSdk 23
        targetSdk 35
        versionCode 264
        versionName '2.6.4'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
